language: java
script: gradle magicspellsBuild -PDeploymentNaming
jdk:
    - oraclejdk8
branches:
  except:
  - volatile
before_deploy:
  - gem install octokit -v 4.3.0
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: R/NDbeD698sdnzxt0i5Jac57gVnwdV7ORNvX0EnNCOi+MazSontIN5QMerY5UwohDxLmIA75jT61ZBqt28DzOUHOHiHi9jLjbNsQVuSvVwCcgx3hS9VQOlJqKX6PDJBqbWGx8gfWpTe30AlEWWDKlr+jUsjx1Iwtvtd53BYEEhgaYEGda9m7vZ0EeLkMK0TkRpUOwoyIWsBK853hG7wl9PD8Ytn0JqAQSaIC/D/ZJ0RjRoI9piCEtsKs0tzRxY0wQuwc8bTGxyCpAMvsR9ZCA8/bocMbifddTSQ4OBCu6ah4q7CZ8pPiAm6CACtnvffUzJeCz2IRlDZbTU1H9OJu25mGrXMMxtQBzEgf6YM53F2Ii2wy6LtS0J4yi/LGmxomhd7gWh8LxuDE/qg5T608Jx8hdvP2ZigpBKJhToEoO0du3+r6lJrCKqeKUHJ0XlMerUao0w9a57W5d8Q9hFUSquDtwd5n0/hh5Hg2kPXLA+UQ4KzzvGPnlZj0G1gvzBltk50u+8cSV7UUw+1LaMsuv+yG8W98mlocfpyW7kQOBalX/9x5ArQHroSM5OQYKGY2aj8wtRmBeqwWgBWuX/TFc0Zbv6LMW1hmf+Fz5OEafG6jeaiOJ78c3u+dawyzDygBPCl3J6zPwv4RD8JY4mGUwl3+TsXNQNcUWTf3ai7hoKM=
  file:
    - "dist/MagicSpells.jar"
    - "dist/MagicSpellsFactions.jar"
    - "dist/MagicSpellsMemory.jar"
    - "dist/MagicSpellsShop.jar"
    - "dist/MagicSpellsTeams.jar"
    - "dist/MagicSpellsTowny.jar"
  on:
    repo: TheComputerGeek2/MagicSpells
